# Spring Framework Configuration | Spring框架配置
spring:
  # DataSource Configuration | 数据源配置
  datasource:
    # Database Driver Class Name | 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Database Connection URL | 数据库连接URL
    # serverTimezone=Asia/Shanghai: Set server timezone to Shanghai | 设置服务器时区为上海
    # useUnicode=true: Enable Unicode support | 启用Unicode支持
    # characterEncoding=utf-8: Set character encoding to UTF-8 | 设置字符编码为UTF-8
    # allowPublicKeyRetrieval=true: Allow public key retrieval | 允许公钥检索
    # useSSL=false: Disable SSL connection | 禁用SSL连接
    url: jdbc:mysql://192.168.56.10:3306/canbe_blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false
    # Database Username | 数据库用户名
    username: root
    # Database Password | 数据库密码
    password: root
  # Redis Configuration | Redis配置
  data:
    redis:
      # Redis Server Port | Redis服务器端口
      port: 6379
      # Redis Server Host | Redis服务器主机地址
      host: 192.168.56.10

mybatis-plus:
  # Mapper XML文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    # 驼峰转下划线
    map-underscore-to-camel-case: true

